spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always

app:
  rabbit:
    exchange: notification.exchange
    email-queue: email.queue
    email-routing-key: notification.email